name: Build KsDumper EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore All Dependencies
        run: nuget restore KsDumper11.sln

      - name: Build DarkControls
        run: msbuild DarkControls\DarkControls.csproj /p:Configuration=Release /p:Platform="AnyCPU"
        shell: cmd

      - name: Build DriverInterface
        run: msbuild DriverInterface\DriverInterface.csproj /p:Configuration=Release /p:Platform="AnyCPU"
        shell: cmd

      - name: Build KsDumper11
        run: msbuild KsDumper11\KsDumper11.csproj /p:Configuration=Release /p:Platform="x86" /p:OutputPath=bin\x86\Release
        shell: cmd

      - name: Upload Everything
        uses: actions/upload-artifact@v4
        with:
          name: KsDumper-Full-Build
          path: KsDumper11/bin/x86/Release/
